# Generated by Django 5.0.3 on 2024-04-02 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('published_at', models.DateField(auto_now=True)),
                ('poster', models.ImageField(upload_to='blog')),
                ('author', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name="To'liq ism")),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='profile')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('poster', models.ImageField(upload_to='')),
                ('link', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percentage', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='BlogModel',
            new_name='About',
        ),
        migrations.DeleteModel(
            name='ProfileModel',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='ServiceModel',
        ),
        migrations.DeleteModel(
            name='SkillModel',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app3.category'),
        ),
        migrations.DeleteModel(
            name='ProjectModel',
        ),
    ]
