# Generated by Django 4.2.11 on 2024-04-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_blog_profile_project_service_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed_at',
            field=models.DateField(null=True),
        ),
    ]
